blank_issues_enabled: false
contact_links:
  - name: Comments and general discussion
    url: https://github.com/ArtfulRascal8/XRKart-64/discussions
    about: Ask questions, leave feedback, and talk with other XRKart 64 players.
